"""initial schema

Revision ID: 570ba6474496
Revises: 
Create Date: 2026-06-30 12:41:53.997337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '570ba6474496'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_accounts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_accounts_name'), ['name'], unique=False)

    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate_to_base', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currency_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_rates_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_rates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_currency_rates_rate_date'), ['rate_date'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_type', sa.String(length=50), nullable=False),
    sa.Column('customer_status', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('tax_office', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('default_invoice_type', sa.String(length=50), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('default_payment_term_days', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('risk_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_short_name'), ['short_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_tax_number'), ['tax_number'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_table', sa.String(length=100), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_related_id'), ['related_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_related_table'), ['related_table'], unique=False)

    op.create_table('service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_cost_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('default_cost_currency', sa.String(length=10), nullable=False),
    sa.Column('default_sale_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('default_sale_currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_items_name'), ['name'], unique=False)

    op.create_table('service_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_sale_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('default_sale_currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_packages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_packages_name'), ['name'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=255), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_setting_key'), ['setting_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('customer_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('contact_role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('is_accounting_contact', sa.Boolean(), nullable=False),
    sa.Column('is_operation_contact', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_contacts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_contacts_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_contacts_id'), ['id'], unique=False)

    op.create_table('monthly_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_revenue_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_event_cost_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_event_expense_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_general_expense_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_allocated_expense_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_profit_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('partner_share_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_periods_closed_by_user_id'), ['closed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_periods_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_periods_period_month'), ['period_month'], unique=True)

    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('ownership_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partners_user_id'), ['user_id'], unique=False)

    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('venue_type', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('stage_info', sa.Text(), nullable=True),
    sa.Column('technical_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venues_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venues_name'), ['name'], unique=False)

    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('manager_partner_id', sa.Integer(), nullable=True),
    sa.Column('default_cost_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('default_cost_currency', sa.String(length=10), nullable=False),
    sa.Column('default_sale_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('default_sale_currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artists_manager_partner_id'), ['manager_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artists_name'), ['name'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('responsible_partner_id', sa.Integer(), nullable=True),
    sa.Column('operation_user_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('invoice_type', sa.String(length=50), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('agreement_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('agreement_currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_agreement_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_customer_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_period_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operation_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_code'), ['event_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_operation_user_id'), ['operation_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_responsible_partner_id'), ['responsible_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_venue_id'), ['venue_id'], unique=False)

    op.create_table('monthly_partner_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_period_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('profit_share_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('collections_on_partner_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expenses_paid_by_partner_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('previous_balance_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_payable_to_partner_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_receivable_from_partner_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monthly_period_id'], ['monthly_periods.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_partner_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_partner_summaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_partner_summaries_monthly_period_id'), ['monthly_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_partner_summaries_partner_id'), ['partner_id'], unique=False)

    op.create_table('artist_rider_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist_rider_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_rider_template_items_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_rider_template_items_id'), ['id'], unique=False)

    op.create_table('carry_forward_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carry_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_period_id', sa.Integer(), nullable=True),
    sa.Column('target_period_id', sa.Integer(), nullable=True),
    sa.Column('source_period_month', sa.String(length=7), nullable=True),
    sa.Column('target_period_month', sa.String(length=7), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('cash_account_id', sa.Integer(), nullable=True),
    sa.Column('source_reference_type', sa.String(length=80), nullable=True),
    sa.Column('source_reference_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remaining_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('carry_reason', sa.Text(), nullable=False),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closure_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.ForeignKeyConstraint(['source_period_id'], ['monthly_periods.id'], ),
    sa.ForeignKeyConstraint(['target_period_id'], ['monthly_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carry_forward_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carry_forward_items_approved_by_user_id'), ['approved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_carry_type'), ['carry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_cash_account_id'), ['cash_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_closed_by_user_id'), ['closed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_service_item_id'), ['service_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_source_period_id'), ['source_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_source_period_month'), ['source_period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_source_reference_id'), ['source_reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_source_reference_type'), ['source_reference_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_target_period_id'), ['target_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carry_forward_items_target_period_month'), ['target_period_month'], unique=False)

    op.create_table('event_financial_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('monthly_period_id', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=True),
    sa.Column('closure_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('agreement_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('planned_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('collected_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remaining_customer_receivable_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_event_cost_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_expense_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remaining_supplier_payable_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('partner_cash_on_hand_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('company_receivable_from_partner_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('company_payable_to_partner_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('operational_profit_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('distributable_profit_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('partner_share_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_agreement_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_payment_plan_matched', sa.Boolean(), nullable=False),
    sa.Column('is_collection_completed', sa.Boolean(), nullable=False),
    sa.Column('are_costs_completed', sa.Boolean(), nullable=False),
    sa.Column('are_expenses_completed', sa.Boolean(), nullable=False),
    sa.Column('are_supplier_debts_closed_or_carried', sa.Boolean(), nullable=False),
    sa.Column('are_partner_cash_items_closed_or_carried', sa.Boolean(), nullable=False),
    sa.Column('is_profit_calculated', sa.Boolean(), nullable=False),
    sa.Column('is_partner_share_calculated', sa.Boolean(), nullable=False),
    sa.Column('prepared_by_user_id', sa.Integer(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('closing_note', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['monthly_period_id'], ['monthly_periods.id'], ),
    sa.ForeignKeyConstraint(['prepared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reopened_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_financial_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_financial_closures_approved_by_user_id'), ['approved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_financial_closures_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_financial_closures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_financial_closures_monthly_period_id'), ['monthly_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_financial_closures_period_month'), ['period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_financial_closures_prepared_by_user_id'), ['prepared_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_financial_closures_reopened_by_user_id'), ['reopened_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_financial_closures_status'), ['status'], unique=False)

    op.create_table('event_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sale_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sale_currency', sa.String(length=10), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost_currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_sale_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('base_cost_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_items_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_items_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_items_service_item_id'), ['service_item_id'], unique=False)

    op.create_table('event_profit_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('revenue_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('artist_cost_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('operation_expense_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('other_expense_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_profit_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('partner_share_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_profit_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_profit_snapshots_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_profit_snapshots_id'), ['id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('paid_by_partner_id', sa.Integer(), nullable=True),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_allocated', sa.Boolean(), nullable=False),
    sa.Column('allocation_start_month', sa.String(length=7), nullable=True),
    sa.Column('allocation_end_month', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['paid_by_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_paid_by_partner_id'), ['paid_by_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_paid_by_user_id'), ['paid_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_title'), ['title'], unique=False)

    op.create_table('financial_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('movement_group_key', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('cash_account_id', sa.Integer(), nullable=True),
    sa.Column('monthly_period_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=80), nullable=False),
    sa.Column('account_area', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('customer_effect', sa.String(length=80), nullable=False),
    sa.Column('cash_effect', sa.String(length=80), nullable=False),
    sa.Column('partner_effect', sa.String(length=80), nullable=False),
    sa.Column('profit_effect', sa.String(length=80), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('reversed_movement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['monthly_period_id'], ['monthly_periods.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['reversed_movement_id'], ['financial_movements.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_movements_account_area'), ['account_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_approved_by_user_id'), ['approved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_cash_account_id'), ['cash_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_monthly_period_id'), ['monthly_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_movement_date'), ['movement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_movement_group_key'), ['movement_group_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_period_month'), ['period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_reversed_movement_id'), ['reversed_movement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_service_item_id'), ['service_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_movements_status'), ['status'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('offer_no', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('advance_payment_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('advance_payment_currency', sa.String(length=10), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('customer_visible_notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('agreement_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_offer_no'), ['offer_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_offers_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_venue_id'), ['venue_id'], unique=False)

    op.create_table('operation_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_notes_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_notes_user_id'), ['user_id'], unique=False)

    op.create_table('operation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_tasks_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_tasks_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_tasks_id'), ['id'], unique=False)

    op.create_table('partner_account_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('monthly_period_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_settled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['monthly_period_id'], ['monthly_periods.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_account_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_account_movements_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_account_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_account_movements_monthly_period_id'), ['monthly_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_account_movements_partner_id'), ['partner_id'], unique=False)

    op.create_table('payment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_plans_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plans_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plans_id'), ['id'], unique=False)

    op.create_table('service_package_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=50), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('program_section', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_cost_currency', sa.String(length=10), nullable=False),
    sa.Column('unit_sale_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_sale_currency', sa.String(length=10), nullable=False),
    sa.Column('total_cost_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_sale_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_visible_on_offer', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_package_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_package_items_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_package_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_package_items_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_package_items_service_item_id'), ['service_item_id'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('payment_plan_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('received_by_user_id', sa.Integer(), nullable=True),
    sa.Column('received_by_partner_id', sa.Integer(), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('current_location', sa.String(length=50), nullable=False),
    sa.Column('is_transferred_to_company', sa.Boolean(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.ForeignKeyConstraint(['received_by_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_collection_date'), ['collection_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_payment_plan_id'), ['payment_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_received_by_partner_id'), ['received_by_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_received_by_user_id'), ['received_by_user_id'], unique=False)

    op.create_table('event_rider_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('template_item_id', sa.Integer(), nullable=True),
    sa.Column('checked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('problem_note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['checked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['artist_rider_template_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_rider_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_rider_checks_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_rider_checks_checked_by_user_id'), ['checked_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_rider_checks_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_rider_checks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_rider_checks_template_item_id'), ['template_item_id'], unique=False)

    op.create_table('event_supplier_payables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('payable_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('remaining_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_carried_forward', sa.Boolean(), nullable=False),
    sa.Column('carry_forward_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['carry_forward_item_id'], ['carry_forward_items.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_supplier_payables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_approved_by_user_id'), ['approved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_carry_forward_item_id'), ['carry_forward_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_payable_type'), ['payable_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_service_item_id'), ['service_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payables_title'), ['title'], unique=False)

    op.create_table('expense_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('allocated_base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_allocations_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_allocations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_allocations_period_month'), ['period_month'], unique=False)

    op.create_table('offer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_package_item_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('program_section', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('internal_unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('internal_cost_currency', sa.String(length=10), nullable=False),
    sa.Column('internal_total_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_visible_on_offer', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['service_items.id'], ),
    sa.ForeignKeyConstraint(['source_package_item_id'], ['service_package_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offer_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offer_items_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_items_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_items_service_item_id'), ['service_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offer_items_source_package_item_id'), ['source_package_item_id'], unique=False)

    op.create_table('cash_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('from_partner_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_cash_account_id', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transfer_method', sa.String(length=50), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('print_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['from_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_cash_account_id'], ['cash_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_transfers_approved_by_user_id'), ['approved_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transfers_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transfers_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transfers_from_partner_id'), ['from_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transfers_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transfers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transfers_to_cash_account_id'), ['to_cash_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_transfers_transfer_date'), ['transfer_date'], unique=False)

    op.create_table('customer_account_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('payment_plan_id', sa.Integer(), nullable=True),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('movement_type', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detail_note', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('collected_by_partner_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('reference_type', sa.String(length=80), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['collected_by_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_account_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_account_movements_collected_by_partner_id'), ['collected_by_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_movement_date'), ['movement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_account_movements_payment_plan_id'), ['payment_plan_id'], unique=False)

    op.create_table('event_supplier_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payable_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('paid_by_partner_id', sa.Integer(), nullable=True),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cash_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cash_account_id'], ['cash_accounts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['paid_by_partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payable_id'], ['event_supplier_payables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_supplier_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_cash_account_id'), ['cash_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_document_no'), ['document_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_paid_by_partner_id'), ['paid_by_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_paid_by_user_id'), ['paid_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_payable_id'), ['payable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_supplier_payments_payment_date'), ['payment_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_supplier_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_payment_date'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_payable_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_paid_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_paid_by_partner_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_document_no'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payments_cash_account_id'))

    op.drop_table('event_supplier_payments')
    with op.batch_alter_table('customer_account_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_payment_plan_id'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_movement_date'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_id'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_event_id'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_document_no'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_direction'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_collection_id'))
        batch_op.drop_index(batch_op.f('ix_customer_account_movements_collected_by_partner_id'))

    op.drop_table('customer_account_movements')
    with op.batch_alter_table('cash_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_transfers_transfer_date'))
        batch_op.drop_index(batch_op.f('ix_cash_transfers_to_cash_account_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transfers_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transfers_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transfers_from_partner_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transfers_document_no'))
        batch_op.drop_index(batch_op.f('ix_cash_transfers_collection_id'))
        batch_op.drop_index(batch_op.f('ix_cash_transfers_approved_by_user_id'))

    op.drop_table('cash_transfers')
    with op.batch_alter_table('offer_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offer_items_source_package_item_id'))
        batch_op.drop_index(batch_op.f('ix_offer_items_service_item_id'))
        batch_op.drop_index(batch_op.f('ix_offer_items_offer_id'))
        batch_op.drop_index(batch_op.f('ix_offer_items_id'))
        batch_op.drop_index(batch_op.f('ix_offer_items_artist_id'))

    op.drop_table('offer_items')
    with op.batch_alter_table('expense_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_allocations_period_month'))
        batch_op.drop_index(batch_op.f('ix_expense_allocations_id'))
        batch_op.drop_index(batch_op.f('ix_expense_allocations_expense_id'))

    op.drop_table('expense_allocations')
    with op.batch_alter_table('event_supplier_payables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_title'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_status'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_service_item_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_payable_type'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_due_date'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_carry_forward_item_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_artist_id'))
        batch_op.drop_index(batch_op.f('ix_event_supplier_payables_approved_by_user_id'))

    op.drop_table('event_supplier_payables')
    with op.batch_alter_table('event_rider_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_rider_checks_template_item_id'))
        batch_op.drop_index(batch_op.f('ix_event_rider_checks_id'))
        batch_op.drop_index(batch_op.f('ix_event_rider_checks_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_rider_checks_checked_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_rider_checks_artist_id'))

    op.drop_table('event_rider_checks')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_received_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_collections_received_by_partner_id'))
        batch_op.drop_index(batch_op.f('ix_collections_payment_plan_id'))
        batch_op.drop_index(batch_op.f('ix_collections_id'))
        batch_op.drop_index(batch_op.f('ix_collections_event_id'))
        batch_op.drop_index(batch_op.f('ix_collections_document_no'))
        batch_op.drop_index(batch_op.f('ix_collections_customer_id'))
        batch_op.drop_index(batch_op.f('ix_collections_collection_date'))

    op.drop_table('collections')
    with op.batch_alter_table('service_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_package_items_service_item_id'))
        batch_op.drop_index(batch_op.f('ix_service_package_items_package_id'))
        batch_op.drop_index(batch_op.f('ix_service_package_items_id'))
        batch_op.drop_index(batch_op.f('ix_service_package_items_artist_id'))

    op.drop_table('service_package_items')
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_plans_id'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_event_id'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_due_date'))

    op.drop_table('payment_plans')
    with op.batch_alter_table('partner_account_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_account_movements_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partner_account_movements_monthly_period_id'))
        batch_op.drop_index(batch_op.f('ix_partner_account_movements_id'))
        batch_op.drop_index(batch_op.f('ix_partner_account_movements_event_id'))

    op.drop_table('partner_account_movements')
    with op.batch_alter_table('operation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_operation_tasks_event_id'))
        batch_op.drop_index(batch_op.f('ix_operation_tasks_assigned_to_user_id'))

    op.drop_table('operation_tasks')
    with op.batch_alter_table('operation_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_operation_notes_id'))
        batch_op.drop_index(batch_op.f('ix_operation_notes_event_id'))

    op.drop_table('operation_notes')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_venue_id'))
        batch_op.drop_index(batch_op.f('ix_offers_package_id'))
        batch_op.drop_index(batch_op.f('ix_offers_offer_no'))
        batch_op.drop_index(batch_op.f('ix_offers_id'))
        batch_op.drop_index(batch_op.f('ix_offers_event_id'))
        batch_op.drop_index(batch_op.f('ix_offers_customer_id'))

    op.drop_table('offers')
    with op.batch_alter_table('financial_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_movements_status'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_source_type'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_source_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_service_item_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_reversed_movement_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_period_month'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_partner_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_movement_group_key'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_movement_date'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_monthly_period_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_event_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_document_no'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_direction'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_customer_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_cash_account_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_artist_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_approved_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_financial_movements_account_area'))

    op.drop_table('financial_movements')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_title'))
        batch_op.drop_index(batch_op.f('ix_expenses_paid_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_paid_by_partner_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_event_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_document_no'))
        batch_op.drop_index(batch_op.f('ix_expenses_artist_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('event_profit_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_profit_snapshots_id'))
        batch_op.drop_index(batch_op.f('ix_event_profit_snapshots_event_id'))

    op.drop_table('event_profit_snapshots')
    with op.batch_alter_table('event_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_items_service_item_id'))
        batch_op.drop_index(batch_op.f('ix_event_items_id'))
        batch_op.drop_index(batch_op.f('ix_event_items_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_items_artist_id'))

    op.drop_table('event_items')
    with op.batch_alter_table('event_financial_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_status'))
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_reopened_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_prepared_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_period_month'))
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_monthly_period_id'))
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_id'))
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_financial_closures_approved_by_user_id'))

    op.drop_table('event_financial_closures')
    with op.batch_alter_table('carry_forward_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_target_period_month'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_target_period_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_status'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_source_reference_type'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_source_reference_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_source_period_month'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_source_period_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_service_item_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_partner_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_event_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_due_date'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_customer_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_closed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_cash_account_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_carry_type'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_artist_id'))
        batch_op.drop_index(batch_op.f('ix_carry_forward_items_approved_by_user_id'))

    op.drop_table('carry_forward_items')
    with op.batch_alter_table('artist_rider_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_rider_template_items_id'))
        batch_op.drop_index(batch_op.f('ix_artist_rider_template_items_artist_id'))

    op.drop_table('artist_rider_template_items')
    with op.batch_alter_table('monthly_partner_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_partner_summaries_partner_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_partner_summaries_monthly_period_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_partner_summaries_id'))

    op.drop_table('monthly_partner_summaries')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_venue_id'))
        batch_op.drop_index(batch_op.f('ix_events_title'))
        batch_op.drop_index(batch_op.f('ix_events_responsible_partner_id'))
        batch_op.drop_index(batch_op.f('ix_events_operation_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_events_event_code'))
        batch_op.drop_index(batch_op.f('ix_events_customer_id'))

    op.drop_table('events')
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artists_name'))
        batch_op.drop_index(batch_op.f('ix_artists_manager_partner_id'))
        batch_op.drop_index(batch_op.f('ix_artists_id'))

    op.drop_table('artists')
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venues_name'))
        batch_op.drop_index(batch_op.f('ix_venues_id'))
        batch_op.drop_index(batch_op.f('ix_venues_customer_id'))

    op.drop_table('venues')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_user_id'))
        batch_op.drop_index(batch_op.f('ix_partners_id'))

    op.drop_table('partners')
    with op.batch_alter_table('monthly_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_periods_period_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_periods_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_periods_closed_by_user_id'))

    op.drop_table('monthly_periods')
    with op.batch_alter_table('customer_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_customer_contacts_full_name'))
        batch_op.drop_index(batch_op.f('ix_customer_contacts_customer_id'))

    op.drop_table('customer_contacts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_record_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_setting_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_id'))

    op.drop_table('system_settings')
    with op.batch_alter_table('service_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_packages_name'))
        batch_op.drop_index(batch_op.f('ix_service_packages_id'))

    op.drop_table('service_packages')
    with op.batch_alter_table('service_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_items_name'))
        batch_op.drop_index(batch_op.f('ix_service_items_id'))

    op.drop_table('service_items')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_related_table'))
        batch_op.drop_index(batch_op.f('ix_documents_related_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_document_no'))

    op.drop_table('documents')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_tax_number'))
        batch_op.drop_index(batch_op.f('ix_customers_short_name'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))

    op.drop_table('customers')
    with op.batch_alter_table('currency_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currency_rates_rate_date'))
        batch_op.drop_index(batch_op.f('ix_currency_rates_id'))
        batch_op.drop_index(batch_op.f('ix_currency_rates_currency'))

    op.drop_table('currency_rates')
    with op.batch_alter_table('cash_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_cash_accounts_id'))

    op.drop_table('cash_accounts')
    # ### end Alembic commands ###
