"""operations

Revision ID: ad5e201515bb
Revises: ac819f2224dc
Create Date: 2026-10-05 23:56:52.671640
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ad5e201515bb"
down_revision: str | None = "ac819f2224dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("assigned_to_id", sa.Integer(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("due_time", sa.Time(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_id"], ["users.id"], name=op.f("fk_event_tasks_assigned_to_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_id"], ["users.id"], name=op.f("fk_event_tasks_completed_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_tasks_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_tasks")),
    )
    op.create_index(
        op.f("ix_event_tasks_assigned_to_id"), "event_tasks", ["assigned_to_id"], unique=False
    )
    op.create_index(op.f("ix_event_tasks_event_id"), "event_tasks", ["event_id"], unique=False)
    op.create_index(op.f("ix_event_tasks_status"), "event_tasks", ["status"], unique=False)
    op.create_table(
        "operation_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("actual_guest_count", sa.Integer(), nullable=True),
        sa.Column("went_well", sa.Text(), nullable=True),
        sa.Column("issues", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_operation_reports_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
            name=op.f("fk_operation_reports_submitted_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_reports")),
        sa.UniqueConstraint("event_id", name=op.f("uq_operation_reports_event_id")),
    )
    op.create_table(
        "rider_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=True),
        sa.Column("rider_item_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_by_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"], ["artists.id"], name=op.f("fk_rider_checks_artist_id_artists")
        ),
        sa.ForeignKeyConstraint(
            ["checked_by_id"], ["users.id"], name=op.f("fk_rider_checks_checked_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_rider_checks_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rider_item_id"],
            ["artist_rider_items.id"],
            name=op.f("fk_rider_checks_rider_item_id_artist_rider_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rider_checks")),
    )
    op.create_index(op.f("ix_rider_checks_event_id"), "rider_checks", ["event_id"], unique=False)
    op.create_index(op.f("ix_rider_checks_status"), "rider_checks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rider_checks_status"), table_name="rider_checks")
    op.drop_index(op.f("ix_rider_checks_event_id"), table_name="rider_checks")
    op.drop_table("rider_checks")
    op.drop_table("operation_reports")
    op.drop_index(op.f("ix_event_tasks_status"), table_name="event_tasks")
    op.drop_index(op.f("ix_event_tasks_event_id"), table_name="event_tasks")
    op.drop_index(op.f("ix_event_tasks_assigned_to_id"), table_name="event_tasks")
    op.drop_table("event_tasks")
    # ### end Alembic commands ###
