"""exchange_rates

Revision ID: 3b2df8b3cbf1
Revises: ad5e201515bb
Create Date: 2026-10-06 05:12:01.983856
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3b2df8b3cbf1"
down_revision: str | None = "ad5e201515bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"], ["users.id"], name=op.f("fk_exchange_rates_updated_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_rates")),
        sa.UniqueConstraint("day", "currency", name=op.f("uq_exchange_rates_day")),
    )
    op.create_index(op.f("ix_exchange_rates_day"), "exchange_rates", ["day"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exchange_rates_day"), table_name="exchange_rates")
    op.drop_table("exchange_rates")
    # ### end Alembic commands ###
