"""expense_allocation_season

Revision ID: a80f182205d6
Revises: 3b2df8b3cbf1
Create Date: 2026-10-06 07:20:57.712560
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a80f182205d6"
down_revision: str | None = "3b2df8b3cbf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_settings",
        sa.Column("season_start_month", sa.Integer(), server_default="1", nullable=False),
    )
    op.add_column(
        "expenses",
        sa.Column("allocation", sa.String(length=15), server_default="month", nullable=False),
    )
    op.add_column("expenses", sa.Column("spread_from", sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "spread_from")
    op.drop_column("expenses", "allocation")
    op.drop_column("company_settings", "season_start_month")
    # ### end Alembic commands ###
