"""user must change password

Revision ID: 37c5163128f2
Revises: a80f182205d6
Create Date: 2026-10-07 08:01:13.994196
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "37c5163128f2"
down_revision: str | None = "a80f182205d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "must_change_password", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "must_change_password")
    # ### end Alembic commands ###
