"""finance ledger

Revision ID: 7be6f5fcf56a
Revises: 393606f76758
Create Date: 2026-10-05 22:31:27.091848
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7be6f5fcf56a"
down_revision: str | None = "393606f76758"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("account_type", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("iban", sa.String(length=40), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_accounts")),
    )
    op.create_table(
        "accounting_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_id"], ["users.id"], name=op.f("fk_accounting_periods_closed_by_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounting_periods")),
        sa.UniqueConstraint("month", name=op.f("uq_accounting_periods_month")),
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_no", sa.String(length=30), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("reverses_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_journal_entries_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_journal_entries_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_entries_reverses_id_journal_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
        sa.UniqueConstraint("entry_no", name=op.f("uq_journal_entries_entry_no")),
        sa.UniqueConstraint("reverses_id", name=op.f("uq_journal_entries_reverses_id")),
    )
    op.create_index(
        op.f("ix_journal_entries_entry_date"), "journal_entries", ["entry_date"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_event_id"), "journal_entries", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_journal_entries_kind"), "journal_entries", ["kind"], unique=False)
    op.create_table(
        "payment_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_payment_plans_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_plans")),
    )
    op.create_index(op.f("ix_payment_plans_event_id"), "payment_plans", ["event_id"], unique=False)
    op.create_table(
        "cash_transfers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=False),
        sa.Column("from_account_id", sa.Integer(), nullable=False),
        sa.Column("to_account_id", sa.Integer(), nullable=False),
        sa.Column("from_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("from_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("to_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("to_rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_cash_transfers_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["from_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_cash_transfers_from_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["to_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_cash_transfers_to_account_id_cash_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_transfers")),
    )
    op.create_index(op.f("ix_cash_transfers_status"), "cash_transfers", ["status"], unique=False)
    op.create_index(
        op.f("ix_cash_transfers_transfer_date"), "cash_transfers", ["transfer_date"], unique=False
    )
    op.create_table(
        "collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("collection_no", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("collection_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("applied_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cash_account_id", sa.Integer(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("document_no", sa.String(length=60), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(cash_account_id IS NULL) <> (partner_id IS NULL)",
            name=op.f("ck_collections_one_destination"),
        ),
        sa.ForeignKeyConstraint(
            ["cash_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_collections_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_collections_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_collections_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_collections_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_collections_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name=op.f("fk_collections_partner_id_partners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("collection_no", name=op.f("uq_collections_collection_no")),
    )
    op.create_index(
        op.f("ix_collections_collection_date"), "collections", ["collection_date"], unique=False
    )
    op.create_index(
        op.f("ix_collections_customer_id"), "collections", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_collections_event_id"), "collections", ["event_id"], unique=False)
    op.create_index(op.f("ix_collections_status"), "collections", ["status"], unique=False)
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_no", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("paid_by", sa.String(length=10), nullable=False),
        sa.Column("cash_account_id", sa.Integer(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("document_no", sa.String(length=60), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("entry_id", sa.Integer(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cash_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_expenses_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["journal_entries.id"], name=op.f("fk_expenses_entry_id_journal_entries")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_expenses_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name=op.f("fk_expenses_partner_id_partners")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_expenses_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint("expense_no", name=op.f("uq_expenses_expense_no")),
    )
    op.create_index(op.f("ix_expenses_event_id"), "expenses", ["event_id"], unique=False)
    op.create_index(op.f("ix_expenses_expense_date"), "expenses", ["expense_date"], unique=False)
    op.create_index(op.f("ix_expenses_status"), "expenses", ["status"], unique=False)
    op.create_table(
        "partner_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("tx_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("cash_account_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cash_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_partner_transactions_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_partner_transactions_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["partners.id"],
            name=op.f("fk_partner_transactions_partner_id_partners"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partner_transactions")),
    )
    op.create_index(
        op.f("ix_partner_transactions_partner_id"),
        "partner_transactions",
        ["partner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_partner_transactions_status"), "partner_transactions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_partner_transactions_tx_date"), "partner_transactions", ["tx_date"], unique=False
    )
    op.create_table(
        "payables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("event_item_id", sa.Integer(), nullable=True),
        sa.Column("expense_id", sa.Integer(), nullable=True),
        sa.Column("artist_id", sa.Integer(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"], ["artists.id"], name=op.f("fk_payables_artist_id_artists")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_payables_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["event_item_id"],
            ["event_items.id"],
            name=op.f("fk_payables_event_item_id_event_items"),
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"], ["expenses.id"], name=op.f("fk_payables_expense_id_expenses")
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["suppliers.id"], name=op.f("fk_payables_supplier_id_suppliers")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payables")),
        sa.UniqueConstraint("expense_id", name=op.f("uq_payables_expense_id")),
    )
    op.create_index(op.f("ix_payables_artist_id"), "payables", ["artist_id"], unique=False)
    op.create_index(op.f("ix_payables_event_id"), "payables", ["event_id"], unique=False)
    op.create_index(op.f("ix_payables_event_item_id"), "payables", ["event_item_id"], unique=False)
    op.create_index(op.f("ix_payables_status"), "payables", ["status"], unique=False)
    op.create_index(op.f("ix_payables_supplier_id"), "payables", ["supplier_id"], unique=False)
    op.create_table(
        "journal_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(length=30), nullable=False),
        sa.Column("debit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("cash_account_id", sa.Integer(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("payable_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("memo", sa.String(length=300), nullable=True),
        sa.CheckConstraint("(debit = 0) <> (credit = 0)", name=op.f("ck_journal_lines_one_side")),
        sa.CheckConstraint(
            "debit >= 0 AND credit >= 0", name=op.f("ck_journal_lines_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["cash_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_journal_lines_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_journal_lines_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_journal_lines_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_journal_lines_event_id_events")
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name=op.f("fk_journal_lines_partner_id_partners")
        ),
        sa.ForeignKeyConstraint(
            ["payable_id"], ["payables.id"], name=op.f("fk_journal_lines_payable_id_payables")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_lines")),
    )
    op.create_index(op.f("ix_journal_lines_account"), "journal_lines", ["account"], unique=False)
    op.create_index(
        op.f("ix_journal_lines_cash_account_id"), "journal_lines", ["cash_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_lines_customer_id"), "journal_lines", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_journal_lines_entry_id"), "journal_lines", ["entry_id"], unique=False)
    op.create_index(op.f("ix_journal_lines_event_id"), "journal_lines", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_journal_lines_partner_id"), "journal_lines", ["partner_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_lines_payable_id"), "journal_lines", ["payable_id"], unique=False
    )
    op.create_table(
        "payable_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_no", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("payable_id", sa.Integer(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("applied_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cash_account_id", sa.Integer(), nullable=True),
        sa.Column("partner_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("document_no", sa.String(length=60), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(cash_account_id IS NULL) <> (partner_id IS NULL)",
            name=op.f("ck_payable_payments_one_source"),
        ),
        sa.ForeignKeyConstraint(
            ["cash_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_payable_payments_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_payable_payments_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name=op.f("fk_payable_payments_partner_id_partners")
        ),
        sa.ForeignKeyConstraint(
            ["payable_id"], ["payables.id"], name=op.f("fk_payable_payments_payable_id_payables")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payable_payments")),
        sa.UniqueConstraint("payment_no", name=op.f("uq_payable_payments_payment_no")),
    )
    op.create_index(
        op.f("ix_payable_payments_payable_id"), "payable_payments", ["payable_id"], unique=False
    )
    op.create_index(
        op.f("ix_payable_payments_payment_date"), "payable_payments", ["payment_date"], unique=False
    )
    op.create_index(
        op.f("ix_payable_payments_status"), "payable_payments", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payable_payments_status"), table_name="payable_payments")
    op.drop_index(op.f("ix_payable_payments_payment_date"), table_name="payable_payments")
    op.drop_index(op.f("ix_payable_payments_payable_id"), table_name="payable_payments")
    op.drop_table("payable_payments")
    op.drop_index(op.f("ix_journal_lines_payable_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_partner_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_event_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_entry_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_customer_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_cash_account_id"), table_name="journal_lines")
    op.drop_index(op.f("ix_journal_lines_account"), table_name="journal_lines")
    op.drop_table("journal_lines")
    op.drop_index(op.f("ix_payables_supplier_id"), table_name="payables")
    op.drop_index(op.f("ix_payables_status"), table_name="payables")
    op.drop_index(op.f("ix_payables_event_item_id"), table_name="payables")
    op.drop_index(op.f("ix_payables_event_id"), table_name="payables")
    op.drop_index(op.f("ix_payables_artist_id"), table_name="payables")
    op.drop_table("payables")
    op.drop_index(op.f("ix_partner_transactions_tx_date"), table_name="partner_transactions")
    op.drop_index(op.f("ix_partner_transactions_status"), table_name="partner_transactions")
    op.drop_index(op.f("ix_partner_transactions_partner_id"), table_name="partner_transactions")
    op.drop_table("partner_transactions")
    op.drop_index(op.f("ix_expenses_status"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_expense_date"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_event_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_collections_status"), table_name="collections")
    op.drop_index(op.f("ix_collections_event_id"), table_name="collections")
    op.drop_index(op.f("ix_collections_customer_id"), table_name="collections")
    op.drop_index(op.f("ix_collections_collection_date"), table_name="collections")
    op.drop_table("collections")
    op.drop_index(op.f("ix_cash_transfers_transfer_date"), table_name="cash_transfers")
    op.drop_index(op.f("ix_cash_transfers_status"), table_name="cash_transfers")
    op.drop_table("cash_transfers")
    op.drop_index(op.f("ix_payment_plans_event_id"), table_name="payment_plans")
    op.drop_table("payment_plans")
    op.drop_index(op.f("ix_journal_entries_kind"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_event_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_entry_date"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_table("accounting_periods")
    op.drop_table("cash_accounts")
    # ### end Alembic commands ###
