"""closings

Revision ID: ac819f2224dc
Revises: 7be6f5fcf56a
Create Date: 2026-10-05 23:30:14.829182
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ac819f2224dc"
down_revision: str | None = "7be6f5fcf56a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_closures",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_by_id", sa.Integer(), nullable=True),
        sa.Column("revenue", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("expense", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("fx", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("profit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("shares", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("reopened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reopen_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_id"], ["users.id"], name=op.f("fk_event_closures_closed_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_event_closures_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_event_closures_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_closures")),
    )
    op.create_index(
        op.f("ix_event_closures_event_id"), "event_closures", ["event_id"], unique=False
    )
    op.create_index(op.f("ix_event_closures_status"), "event_closures", ["status"], unique=False)
    op.create_table(
        "receivable_write_offs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_receivable_write_offs_created_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entries.id"],
            name=op.f("fk_receivable_write_offs_entry_id_journal_entries"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_receivable_write_offs_event_id_events")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_receivable_write_offs")),
    )
    op.create_index(
        op.f("ix_receivable_write_offs_event_id"),
        "receivable_write_offs",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_receivable_write_offs_status"), "receivable_write_offs", ["status"], unique=False
    )
    op.add_column("accounting_periods", sa.Column("entry_id", sa.Integer(), nullable=True))
    op.add_column(
        "accounting_periods",
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "accounting_periods", sa.Column("reopened_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("accounting_periods", sa.Column("reopen_reason", sa.Text(), nullable=True))
    op.create_foreign_key(
        op.f("fk_accounting_periods_entry_id_journal_entries"),
        "accounting_periods",
        "journal_entries",
        ["entry_id"],
        ["id"],
    )
    op.add_column("expenses", sa.Column("spread_until", sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "spread_until")
    op.drop_constraint(
        op.f("fk_accounting_periods_entry_id_journal_entries"),
        "accounting_periods",
        type_="foreignkey",
    )
    op.drop_column("accounting_periods", "reopen_reason")
    op.drop_column("accounting_periods", "reopened_at")
    op.drop_column("accounting_periods", "snapshot")
    op.drop_column("accounting_periods", "entry_id")
    op.drop_index(op.f("ix_receivable_write_offs_status"), table_name="receivable_write_offs")
    op.drop_index(op.f("ix_receivable_write_offs_event_id"), table_name="receivable_write_offs")
    op.drop_table("receivable_write_offs")
    op.drop_index(op.f("ix_event_closures_status"), table_name="event_closures")
    op.drop_index(op.f("ix_event_closures_event_id"), table_name="event_closures")
    op.drop_table("event_closures")
    # ### end Alembic commands ###
